CHANGELOG.md
LICENSE
backend/src/api/poll/controllers/poll.js
pdf-ui/CHANGELOG.md

from DEV to QA

---

backend/database/migrations/20241121_2_WithdrawalsRestoreDataAndDropSchema.js

- Add 
- Added Migration script 2 *** Must be run as second stage of publishing
- [related issue](https://github.com/IntersectMBO/govtool/issues/2378)
- [ x ] My changes generate no new warnings
- [ x ] My code follows the [style guidelines](https://github.com/IntersectMBO/govtool/tree/main/docs/style-guides) of this project
- [ x ] I have commented my code, particularly in hard-to-understand areas

Migration script 2

---

backend/database/migrations/20241121_2_WithdrawalsRestoreDataAndDropSchema.js
backend/public/api-docs/api.yaml
pdf-ui/CHANGELOG.md
pdf-ui/package-lock.json
pdf-ui/package.json
pdf-ui/src/components/CreateGovernanceActionDialog/index.jsx
pdf-ui/src/components/CreationGoveranceAction/Step2.jsx
pdf-ui/src/components/CreationGoveranceAction/Step3.jsx
pdf-ui/src/components/CreationGoveranceAction/WithdrawalsManager.jsx
pdf-ui/src/components/EditProposalDialog/index.jsx

- Fix 
- Added validation for Receiving Stake Address and Amount on creating Treasury Proposal [Issue #2435](https://github.com/IntersectMBO/govtool/issues/2435)
- Fixed test id to match suggested format [Issue #2437](https://github.com/IntersectMBO/govtool/issues/2437)
- Fixed review Stake Addresses and Amounts in Treasury Proposal Review Step and Draft [Issue #2438](https://github.com/IntersectMBO/govtool/issues/2438)
- Fixed edit Stake Addresses and Amounts in Treasury Proposal Review edit form
- [related issue](https://github.com/IntersectMBO/govtool/issues/2435)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2437)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2438)

Dev to QA BugFix #2435 #2437 #2438

---

backend/src/api/proposal/controllers/proposal.js

Fix
-Treasury Proposal Creation validate mandatory stake address and amount [#2435] https://github.com/IntersectMBO/govtool/issues/2435)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2435)

BugFix #2435 backend

---

pdf-ui/CHANGELOG.md
pdf-ui/package-lock.json
pdf-ui/package.json
pdf-ui/src/components/CreationGoveranceAction/Step2.jsx
pdf-ui/src/components/CreationGoveranceAction/Step3.jsx

Fix
- Fix test id on 3rd step
- Fix added one more check for prepopulated field
- [related issue](https://github.com/IntersectMBO/govtool/issues/2438)

3rd fix for #2438

---

backend/src/api/poll-vote/controllers/poll-vote.js
backend/src/api/poll/controllers/poll.js
pdf-ui/CHANGELOG.md
pdf-ui/package-lock.json
pdf-ui/package.json
pdf-ui/src/pages/IdentificationPage/index.jsx

- Added check for already existing active pool [Bug #2507] https://github.com/IntersectMBO/govtool/issues/2507
- Fixed  Unable to vote after opening new voting pool  [Bug #2508] https://github.com/IntersectMBO/govtool/issues/2508
- [Bug #2508] https://github.com/IntersectMBO/govtool/issues/2508
- [Bug #2507] https://github.com/IntersectMBO/govtool/issues/2507

Bugfix #2507, #2508

---

backend/src/api/poll-vote/controllers/poll-vote.js
backend/src/api/poll/controllers/poll.js
pdf-ui/CHANGELOG.md
pdf-ui/package-lock.json
pdf-ui/package.json
pdf-ui/src/lib/utils.js
pdf-ui/src/pages/IdentificationPage/index.jsx

- Fix 
- Changed regex to support IPFS standard for uploading files
- [related issue](https://github.com/IntersectMBO/govtool/issues/2495)

IPFS URL Format support

---

pdf-ui/CHANGELOG.md
pdf-ui/src/pages/ProposedGovernanceActions/index.jsx

- Fix 
- Temporaly fix for  Sorting Icon [Issue #2650](https://github.com/IntersectMBO/govtool/issues/2650)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2650)

Temporaly BugFix Sorting Icon #2650

---

pdf-ui/package-lock.json
pdf-ui/package.json

Change 
- Version changed to 0.5.8

Dev to qa Version changed

---

pdf-ui/CHANGELOG.md
pdf-ui/package-lock.json
pdf-ui/package.json
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx

Add
- Added "Read More" button on proposal page if Character Count is bigger den 500 [Issue #2649](https://github.com/IntersectMBO/govtool/issues/2649)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2649)

Bug fix #2649

---

pdf-ui/CHANGELOG.md
pdf-ui/package-lock.json
pdf-ui/package.json
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx
pdf-ui/src/pages/ProposedGovernanceActions/index.jsx

From Qa to Pre Prod

---

pdf-ui/CHANGELOG.md
pdf-ui/package-lock.json
pdf-ui/package.json
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx
pdf-ui/src/pages/ProposedGovernanceActions/index.jsx

From Pre prod to Main

---

pdf-ui/CHANGELOG.md
pdf-ui/package-lock.json
pdf-ui/package.json
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx
pdf-ui/src/pages/ProposedGovernanceActions/index.jsx

Fom Qa to pre prod

---

backend/database/migrations/20250502_1_add_strapi_api_token_permissions_pk copy.js
backend/database/migrations/20250502_2_Insert_and_update_gov_actions.js
backend/src/api/proposal-content/controllers/proposal-content.js
backend/src/api/proposal/controllers/proposal.js
pdf-ui/CHANGELOG.md
pdf-ui/package-lock.json
pdf-ui/package.json
pdf-ui/src/components/CreateGovernanceActionDialog/index.jsx
pdf-ui/src/components/CreationGoveranceAction/ConstitutionManager.jsx
pdf-ui/src/components/CreationGoveranceAction/LinkManager.jsx
pdf-ui/src/components/CreationGoveranceAction/Step2.jsx
pdf-ui/src/components/CreationGoveranceAction/Step3.jsx
pdf-ui/src/components/CreationGoveranceAction/WithdrawalsManager.jsx
pdf-ui/src/components/CreationGoveranceAction/index.js
pdf-ui/src/components/EditProposalDialog/index.jsx
pdf-ui/src/components/ProposalsList/index.jsx
pdf-ui/src/components/SubmissionGovernanceAction/Steps/InformationStorageStep.jsx

- [Added  option Updates to the Constitution to the dropdown when proposing new GA](https://github.com/IntersectMBO/govtool/issues/2258)
- [Changed: Treasury to Treasury requests and Info to Info Action](https://github.com/IntersectMBO/govtool/issues/2258)
- [Removed Unnecessary Fields Displayed in "Review Your Submission" for Info Proposal](https://github.com/IntersectMBO/govtool/issues/2833)
- note: because of big change on back and front version is change from 0.5.x to 0.6.0 back and front must be updated synchronized
- [related issue](https://github.com/IntersectMBO/govtool/issues/2258)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2833)

Proposal constitution functionality

---

backend/database/migrations/20250502_1_add_strapi_api_token_permissions_pk copy.js

- QuickFix adding PK Migration

QuickFix adding PK Migration

---

pdf-ui/src/components/SubmissionGovernanceAction/Steps/InformationStorageStep.jsx

QuickFix Ga Submition fix

---

.github/workflows/merge.yaml

feat: add build number

---

pdf-ui/package.json

chore: Bump package version

---

CODEOWNERS

- Remove vpaunovic and teske00 as code owners
- Add @nebojsact as code owner

Chore: update codeowners

---

pdf-ui/src/components/BudgetDiscussionInfoSegment/index.jsx
pdf-ui/src/components/index.js
pdf-ui/src/lib/api.js
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

feat: Single bp page init

---

backend/src/api/bd-costing/routes/bd-costing.js
backend/src/api/bd-further-information/routes/bd-further-information.js
backend/src/api/bd-proposal-detail/routes/bd-proposal-detail.js
backend/src/api/bd-proposal-ownership/routes/bd-proposal-ownership.js
backend/src/api/bd-psapb/routes/bd-psapb.js
backend/src/api/bd/controllers/bd.js

fix: Fix bd controller

---

backend/src/api/bd-costing/content-types/bd-costing/schema.json
backend/src/api/bd-proposal-detail/content-types/bd-proposal-detail/schema.json
backend/src/api/bd-psapb/content-types/bd-psapb/schema.json
backend/src/api/bd/content-types/bd/schema.json
backend/src/api/migration/controllers/migration.js
backend/src/api/migration/routes/migration.js
backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json

- Add submissions migration script

Add submission migration script

---

pdf-ui/src/components/BudgetDiscussionInfoSegment/index.jsx
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

feat: Add other fileds on bd single page

---

backend/src/api/bd/content-types/bd/schema.json
backend/src/api/comment/content-types/comment/schema.json
backend/src/api/comment/controllers/comment.js
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

feat: Enable comments on bd

---

backend/src/api/migration/controllers/migration.js

- Add proposal poll creation on migration

feat: create poll for bd proposal on migration

---

backend/src/api/bd/controllers/bd.js
backend/src/api/bd/routes/custom-routes.js

feat: Add endpoint for the bd proposal versions

---

pdf-ui/src/lib/api.js
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

feat: Add getBDPoll function

---

pdf-ui/src/components/BudgetDiscussionPoll/index.jsx
pdf-ui/src/components/index.js
pdf-ui/src/lib/api.js
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

feat: Add BD poll card

---

pdf-ui/src/components/BudgetDiscussionPoll/index.jsx

feat: Only drep can vote on bd poll

---

backend/src/api/bd-poll-vote/routes/bd-poll-vote.js
pdf-ui/src/components/BudgetDiscussionPoll/index.jsx
pdf-ui/src/components/DrepVotersDialog/index.jsx
pdf-ui/src/components/index.js
pdf-ui/src/lib/api.js

feat: Add drep modal

---

backend/src/api/bd-costing/content-types/bd-costing/schema.json
backend/src/api/migration/controllers/migration.js

fix: Fix costing data model

---

pdf-ui/src/components/BudgetDiscussionCard/index.jsx
pdf-ui/src/components/BudgetDiscussionsList/index.jsx
pdf-ui/src/components/CreateBudgetDiscussionDialog/index.jsx
pdf-ui/src/pages/BudgetDiscussion/index.jsx

Budget discussion

---

backend/src/api/bd/controllers/bd.js

feat: Create poll after creation of proposal

---

pdf-ui/package-lock.json
pdf-ui/package.json

version change for build beta 2

---

pdf-ui/package.json

Update pdf version

---

pdf-ui/package.json
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

fix: Fix title on single proposal page

---

pdf-ui/package.json
pdf-ui/src/components/BudgetDiscussionReviewVersions/index.js
pdf-ui/src/components/CreateBudgetDiscussionDialog/index.jsx
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

fix: Fix proposal edit

---

pdf-ui/package.json
pdf-ui/src/components/BudgetDiscussionParts/Costing/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProblemStatementsAndProposalBenefits/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProposalDetails/index.jsx
pdf-ui/src/components/CreateBudgetDiscussionDialog/index.jsx
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx
pdf-ui/src/pages/BudgetDiscussion/index.jsx

fix: Fix create proposal form

---

pdf-ui/package.json
pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionReview/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionSubmit/index.jsx

fix: Fix revire proposal step

---

backend/src/api/bd-contract-type/routes/bd-contract-type.js
backend/src/api/bd-currency-list/routes/bd-currency-list.js
backend/src/api/bd-intersect-committee/routes/bd-intersect-committee.js
backend/src/api/bd-road-map/routes/bd-road-map.js
backend/src/api/bd-type/routes/bd-type.js
backend/src/api/country-list/routes/country-list.js

fix: Fix api permisions

---

backend/src/api/comment/content-types/comment/schema.json
pdf-ui/src/components/CommentCard/Subcomponent/index.jsx
pdf-ui/src/components/CommentCard/UsernameSection/index.jsx
pdf-ui/src/components/CommentCard/index.jsx
pdf-ui/src/components/GlobalWrapper.jsx
pdf-ui/src/lib/helpers.js
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx

feat: Add drep indicator in comments

---

pdf-ui/src/components/DrepVotersDialog/index.jsx
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

feat: Display poll in bd page

---

pdf-ui/package.json
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx

feat: Allow every user to see version button

---

pdf-ui/src/components/BudgetDiscussionCard/index.jsx
pdf-ui/src/components/BudgetDiscussionInfoSegment/index.jsx
pdf-ui/src/components/BudgetDiscussionsList/index.jsx
pdf-ui/src/components/CommentCard/index.jsx
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx
pdf-ui/src/pages/BudgetDiscussion/index.jsx

Fix [Proposal budget] Missing test IDs #3338

---

backend/src/api/bd-contact-information/controllers/bd-contact-information.js
backend/src/api/bd/controllers/bd.js

feat: Hide sensitive bd proposal data

---

pdf-ui/src/components/BudgetDiscussionsList/index.jsx
pdf-ui/src/pages/BudgetDiscussion/index.jsx

- [related issue 1](https://github.com/IntersectMBO/govtool/issues/3334)
- [related issue 2](https://github.com/IntersectMBO/govtool/issues/3328)

3334 search is divided by category

---

pdf-ui/src/components/BudgetDiscussionCard/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionReview/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionSubmit/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ContractInformation/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/Costing/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProposalDetails/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProposalOwnership/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/StepperActionButtons.jsx
pdf-ui/src/components/BudgetDiscussionsList/index.jsx
pdf-ui/src/components/CreateBudgetDiscussionDialog/index.jsx

-  Fix [[Proposal budget submission] Missing test IDs #3339](https://github.com/IntersectMBO/govtool/issues/3339)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3339)

[Proposal budget submission] Missing test IDs #3339

---

pdf-ui/package.json
pdf-ui/src/components/BudgetDiscussionPoll/index.jsx
pdf-ui/src/components/CommentCard/Subcomponent/index.jsx
pdf-ui/src/components/CommentCard/index.jsx
pdf-ui/src/lib/api.js

Fix bd poll voting

---

pdf-ui/package.json
pdf-ui/src/components/BudgetDiscussionPoll/index.jsx

fix: Fix voting

---

pdf-ui/package.json
pdf-ui/src/components/BudgetDiscussionPoll/index.jsx

feat: Add isRegisteredAsSoleVoter condition

---

backend/src/api/bd/controllers/bd.js
backend/src/extensions/users-permissions/strapi-server.js

fix: Fix bd response

---

backend/src/api/bd/controllers/bd.js
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

Fix duplicates

---

pdf-ui/src/components/BudgetDiscussionParts/AdministrationAndAuditing/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionReview/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/Costing/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/FurtherInformation/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProblemStatementsAndProposalBenefits/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProposalDetails/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProposalOwnership/index.jsx
pdf-ui/src/components/CreateBudgetDiscussionDialog/index.jsx

- [Removed Section 1 form application](https://github.com/IntersectMBO/govtool/issues/3396) 
- [related issue](https://github.com/IntersectMBO/govtool/issues/3396)

remove section 1 #3396

---

pdf-ui/src/components/BudgetDiscussionParts/Costing/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProblemStatementsAndProposalBenefits/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProposalDetails/index.jsx
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

- Change
[BugFix: 2500 words limit #3401](https://github.com/IntersectMBO/govtool/issues/3401)
- Fix
[BugFix: maintained and supported question box is now visible](https://github.com/IntersectMBO/govtool/issues/3389) 

Bug fix maintained and supported question box #3389

---

pdf-ui/src/components/BudgetDiscussionParts/Costing/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProblemStatementsAndProposalBenefits/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProposalDetails/index.jsx
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

- Fix 
[BugFix: Proposal shows ADA to USD instead of USD to ADA](https://github.com/IntersectMBO/govtool/issues/3402)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3402)

Bug fix  ada to usd instead of usd to ada #3402

---

backend/src/api/bd/controllers/bd.js
pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionReview/index.jsx
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

FIX Save BD intersect admin further text

---

backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json
pdf-ui/package-lock.json
pdf-ui/src/components/CreateBudgetDiscussionDialog/index.jsx

Fix Validation social_handles

---

backend/package-lock.json
backend/package.json
backend/src/api/bd-poll-vote/controllers/bd-poll-vote.js
backend/src/api/comment/controllers/comment.js
backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json
backend/src/extensions/users-permissions/strapi-server.js
pdf-ui/package.json
pdf-ui/src/components/BudgetDiscussionPoll/index.jsx
pdf-ui/src/components/CommentCard/index.jsx
pdf-ui/src/components/GlobalWrapper.jsx
pdf-ui/src/components/UsernameModal/index.jsx
pdf-ui/src/lib/api.js
pdf-ui/src/lib/axiosInstance.js
pdf-ui/src/lib/helpers.js
pdf-ui/src/lib/utils.js
pdf-ui/src/pages/IdentificationPage/index.jsx

- [related issue](https://github.com/IntersectMBO/govtool/issues/3425)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3332)

Handle drep signing and authorization

---

pdf-ui/package.json
pdf-ui/src/components/CreateBudgetDiscussionDialog/index.jsx
pdf-ui/src/components/GlobalWrapper.jsx
pdf-ui/src/lib/hooks.js

- Add scrollToTop functionality

feat: add scrollToTop functionality

---

pdf-ui/src/components/BudgetDiscussionCard/index.jsx
pdf-ui/src/components/BudgetDiscussionInfoSegment/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionReview/index.jsx
pdf-ui/src/components/BudgetDiscussionReviewVersions/index.js
pdf-ui/src/components/DrepVotersDialog/index.jsx
pdf-ui/src/lib/utils.js
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx
pdf-ui/src/pages/BudgetDiscussion/index.jsx

- Correct ada format everywhere, enable markdown on preview step, enable markdown ul and li formatting
- [related issue](https://github.com/IntersectMBO/govtool/issues/3418)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3427)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3448)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3385)

feat: enable markdown on preview step, add correct ada format everywhere

---

backend/src/api/bd/content-types/bd/schema.json
backend/src/api/bd/controllers/bd.js
backend/src/api/bd/services/bd.js
backend/src/api/comment/controllers/comment.js
backend/src/api/migration/controllers/migration.js
backend/src/api/migration/routes/migration.js
pdf-ui/package.json
pdf-ui/src/components/BudgetDiscussionCard/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/AdministrationAndAuditing/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionReview/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionSubmit/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/Costing/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/FurtherInformation/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProblemStatementsAndProposalBenefits/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProposalDetails/index.jsx
pdf-ui/src/components/BudgetDiscussionParts/ProposalOwnership/index.jsx
pdf-ui/src/components/CreateBudgetDiscussionDialog/index.jsx
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

feat: Add master_id field to bd collection

---

backend/src/api/bd-costing/content-types/bd-costing/schema.json
backend/src/api/migration/controllers/migration.js
backend/src/api/migration/routes/migration.js
backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json

- Add new number fields to bd_costing
- [related issue](https://github.com/IntersectMBO/govtool/issues/3331

feat(#3331): add new fields for amounts in bd_costing

---

pdf-ui/src/components/CreateGovernanceActionDialog/index.jsx
pdf-ui/src/components/CreationGoveranceAction/Step2.jsx

- Fix Inaccurate Validation and UI Issues in Constitution Type Proposal Form [#2965](https://github.com/IntersectMBO/govtool/issues/2965)

Fix for Validation and UI Issues in Constitution Type Proposal Form #2965

---

backend/src/api/migration/controllers/migration.js
backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json

- Handle conversion rates commas

fix: handle commas in conversion rates

---

backend/src/api/bd/controllers/bd.js
backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json
pdf-ui/package.json
pdf-ui/src/components/BudgetDiscussionsList/index.jsx
pdf-ui/src/components/CreateBudgetDiscussionDialog/index.jsx
pdf-ui/src/components/SearchInput/index.jsx
pdf-ui/src/components/index.js
pdf-ui/src/pages/BudgetDiscussion/index.jsx

- Fix search re-render cause, master_id fix null on create, fix delete my-proposals if no user detected, return master_id on create in response

fix: search input, my-proposals reset, master_id on create

---

backend/src/api/bd/controllers/bd.js
backend/src/api/proposal/controllers/proposal.js
backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json
pdf-ui/src/components/BudgetDiscussionCard/index.jsx
pdf-ui/src/components/CommentCard/index.jsx
pdf-ui/src/lib/hooks.js
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

- Handle master id proposed on date
- Handle hyperlinking scrolling for deployed version
- Handle pdf versions review load

fix: handle master proposal create date and hyperlink, fix pdf versions

---

backend/src/api/report/controllers/report.js

comment fix 2

---

backend/src/api/report/controllers/report.js

Check for existing proposal

---

backend/public/api-docs/api.yaml

-  Change update api documentation
- [related issue](https://github.com/IntersectMBO/govtool/issues/3589)

Api documentation update

---

pdf-ui/CHANGELOG.md
pdf-ui/src/components/CommentCard/UsernameSection/index.jsx

-Fix [Proposal budget submission] Missing test IDs (#3339)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3339)

fix/ [Proposal budget submission] Missing test IDs (#3339)

---

pdf-ui/src/components/CreationGoveranceAction/ConstitutionManager.jsx

- Fix unable to update info draft to constitution type proposal
- [related issue](https://github.com/IntersectMBO/govtool/issues/3042)

fix: Unable to Update Info Draft to Constitution-Type Proposal (#3042)

---

pdf-ui/CHANGELOG.md
pdf-ui/package.json

Version change to 29

---

backend/src/api/bd-contact-information/content-types/bd-contact-information/lifecycles.js
backend/src/api/bd-costing/content-types/bd-costing/lifecycles.js
backend/src/api/bd-poll-vote/content-types/bd-poll-vote/lifecycles.js
backend/src/api/bd-poll/content-types/bd-poll/lifecycles.js

- Fix
Creatig Budget Discussion #3644
- [related issue](https://github.com/IntersectMBO/govtool/issues/3644)

Fix for creatig Budget Discussion #3644

---

backend/src/api/bd-poll/content-types/bd-poll/lifecycles.js

- Fix 
Unable to Submit Poll Vote on Budget Proposal as a dRep #3648
- [related issue](https://github.com/IntersectMBO/govtool/issues/3648)

Fix: Unable to Submit Poll Vote on Budget Proposal as a dRep #3648

---

pdf-ui/src/components/CreationGoveranceAction/Step1.jsx
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx

- Add 
Added Hardware Wallet warning #2575
- [related issue](https://github.com/IntersectMBO/govtool/issues/2575)

Hardware Wallet warning #2575

---

pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx

BP not fount redirect

---

backend/src/api/proposal/controllers/proposal.js
pdf-ui/src/components/CreationGoveranceAction/Step1.jsx

Fix get proposal by hash id
- Change
Changed wording for harwdare wallet
- FIX 
Fix get proposal by hash id

Changed wording for harwdare wallet

---

pdf-ui/CHANGELOG.md
pdf-ui/package.json
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx

- Fix DataTestIds and update version
- [related issue](https://github.com/IntersectMBO/govtool/issues/3716)

Fix/duplicate test i ds in proposal details and review modal (#3716)

---

backend/src/api/proposal-content/content-types/proposal-content/schema.json
backend/src/api/proposal-content/controllers/proposal-content.js
backend/src/api/proposal-hard-fork-content/content-types/proposal-hard-fork-content/schema.json
backend/src/api/proposal/controllers/proposal.js
backend/src/api/proxy/controllers/proxy.js
pdf-ui/src/components/BudgetDiscussionParts/StepperActionButtons.jsx
pdf-ui/src/components/CreationGoveranceAction/HardForkManager.jsx
pdf-ui/src/components/CreationGoveranceAction/Step2.jsx
pdf-ui/src/components/CreationGoveranceAction/WithdrawalsManager.jsx
pdf-ui/src/components/EditProposalDialog/index.jsx
pdf-ui/src/components/SubmissionGovernanceAction/Steps/InformationStorageStep.jsx
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx

Fix of hard fork adding and editing

---

pdf-ui/src/components/CommentCard/index.jsx
pdf-ui/src/components/UserValidation/UserValidation.jsx
pdf-ui/src/context/context.jsx
pdf-ui/src/lib/helpers.js
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx
pdf-ui/src/pages/BudgetDiscussion/index.jsx
pdf-ui/src/pages/IdentificationPage/index.jsx
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx
pdf-ui/src/pages/ProposedGovernanceActions/index.jsx

- Change feat: enhance user validation and comment functionality across components
- Fix Replying to comments shows “Failed to comment” error despite successful submission #3780
- [related issue](https://github.com/IntersectMBO/govtool/issues/3549)
- [related issue](https://github.com/IntersectMBO/govtool/issues/3780)

Fix/ move verification modal in proposals to better places (#3549)

---

pdf-ui/CHANGELOG.md
pdf-ui/package-lock.json
pdf-ui/package.json
pdf-ui/src/components/UserValidation/UserValidation.jsx
pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx
pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx

Added pointer to links
-   Fix submit to ga button 
-   Added pointer to links

 Fix submit to ga button
