- backend/src/api/poll-vote/controllers/poll-vote.js
-  Fix: Added control if poll vote already exist for current user 
- [related issue](https://github.com/IntersectMBO/govtool/issues/2356)
> bugfix #2356

- backend/src/api/poll-vote/controllers/poll-vote.js
- backend/src/api/poll/controllers/poll.js
- Fix: Add check for user poll vote mupltiple
> From Dev to QA - 12.11.2024

- backend/database/migrations/20241121_1_WithdrawalsCopyDataToTempSchema.js
- backend/src/api/proposal-content/content-types/proposal-content/schema.json
- backend/src/api/proposal-content/controllers/proposal-content.js
- backend/src/components/proposal/proposal-withdrawals.json
- backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json
- backend/types/generated/components.d.ts
- backend/types/generated/contentTypes.d.ts
- Change 
- Changed structure for withdrawals address in proposal
- Added separated migration script file that will run on next start
- [related issue](https://github.com/IntersectMBO/govtool/issues/2378)
- [ x ] My changes generate no new warnings
- [ x ] My code follows the [style guidelines](https://github.com/IntersectMBO/govtool/tree/main/docs/style-guides) of this project
- [ x ] I have commented my code, particularly in hard-to-understand areas
> Bugfix (change request) #2378 Backend step 1

- backend/public/api-docs/api.yaml
- pdf-ui/CHANGELOG.md
- pdf-ui/package-lock.json
- pdf-ui/package.json
- pdf-ui/src/components/CreateGovernanceActionDialog/index.jsx
- pdf-ui/src/components/CreationGoveranceAction/Step2.jsx
- pdf-ui/src/components/CreationGoveranceAction/Step3.jsx
- pdf-ui/src/components/CreationGoveranceAction/WithdrawalsManager.jsx
- pdf-ui/src/components/EditProposalDialog/index.jsx
- Fix 
- Added validation for Receiving Stake Address and Amount on creating Treasury Proposal [Issue #2435](https://github.com/IntersectMBO/govtool/issues/2435)
- Fixed test id to match suggested format [Issue #2437](https://github.com/IntersectMBO/govtool/issues/2437)
- Fixed review Stake Addresses and Amounts in Treasury Proposal Review Step and Draft [Issue #2438](https://github.com/IntersectMBO/govtool/issues/2438)
- Fixed edit Stake Addresses and Amounts in Treasury Proposal Review edit form
- [related issue](https://github.com/IntersectMBO/govtool/issues/2435)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2437)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2438)
> BugFix #2435 #2437 #2438

- pdf-ui/CHANGELOG.md
- pdf-ui/package.json
- pdf-ui/src/components/CreationGoveranceAction/WithdrawalsManager.jsx
Fix 
-  Fixed duplicated test-id names [related issue #2437](https://github.com/IntersectMBO/govtool/issues/2437)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2437)
> 2nd fix #2437 fixed duplicated test id names

- pdf-ui/CHANGELOG.md
- pdf-ui/package-lock.json
- pdf-ui/package.json
- pdf-ui/src/components/CreationGoveranceAction/Step2.jsx
- pdf-ui/src/components/CreationGoveranceAction/Step3.jsx
- pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx
Fix
- Fix display Stake Address and Amount in Draft [Issue #2438](https://github.com/IntersectMBO/govtool/issues/2438)
- Fix Test Id names in review form [Issue #2437](https://github.com/IntersectMBO/govtool/issues/2437)
- Fix #2357 Display only last Inactive pool [Issue #2357](https://github.com/IntersectMBO/govtool/issues/2357)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2438)
> Bug fix #2438, #2435

- .github/workflows/publish-to-npm.yaml
- set up workflow for publishing the package to npm
* Add `NPM_TOKEN` into secrets
* Specify needed node version (initially set as 20)
> chore: add github workflow to publish package to npm

- backend/src/api/poll-vote/controllers/poll-vote.js
- backend/src/api/poll/controllers/poll.js
- pdf-ui/CHANGELOG.md
- pdf-ui/package-lock.json
- pdf-ui/package.json
- pdf-ui/src/pages/IdentificationPage/index.jsx
- Added check for already existing active pool [Bug #2507](https://github.com/IntersectMBO/govtool/issues/2507)
- Fixed  Unable to vote after opening new voting pool  [Bug #2508](https://github.com/IntersectMBO/govtool/issues/2508)
- Change copy of the proposal discussion forum landing page [Bug #2544](https://github.com/IntersectMBO/govtool/issues/2544)
- [Bug #2508](https://github.com/IntersectMBO/govtool/issues/2508)
- [Bug #2507](https://github.com/IntersectMBO/govtool/issues/2507)
- [Bug#2544](https://github.com/IntersectMBO/govtool/issues/2544)
> Bug fix  #2544

- pdf-ui/CHANGELOG.md
- pdf-ui/src/lib/utils.js
- Fix 
- Changed regex to support IPFS standard for uploading files
- [related issue](https://github.com/IntersectMBO/govtool/issues/2495)
> Allow IPFS url to be used

- pdf-ui/CHANGELOG.md
- pdf-ui/package-lock.json
- pdf-ui/package.json
- pdf-ui/src/pages/ProposedGovernanceActions/SingleGovernanceAction/index.jsx
- pdf-ui/src/pages/ProposedGovernanceActions/index.jsx
> from dev to QA

- pdf-ui/src/components/CreationGoveranceAction/Step2.jsx
- Fix: optional chaining operator
> fix: optional chain operator in step2

- backend/src/api/bd-proposal-detail/content-types/bd-proposal-detail/schema.json
- backend/src/api/migration/controllers/migration.js
- backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json
- Add other_contract_type to migration script and make that field as long text
> Add new field to migrate script

- backend/src/api/migration/controllers/migration.js
- add is_active to true on migration
> feat: add is_active to true on migration creation

- pdf-ui/src/components/BudgetDiscussionCard/index.jsx
- pdf-ui/src/components/BudgetDiscussionReviewVersions/index.js
- pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx
- Add budget label and value to bd card
> feat (#3352): add budget category label and value to budget card

- pdf-ui/src/components/BudgetDiscussionParts/AdministrationAndAuditing/index.jsx
- pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionReview/index.jsx
- pdf-ui/src/components/CommentCard/Subcomponent/index.jsx
- Fix 
BugFix: [Incorrect Display of Administrator Selection on Review Submission Page](https://github.com/IntersectMBO/govtool/issues/3399)
BugFix: [Expanding Comments thread Causes Blank Screen and Console Error ](https://github.com/IntersectMBO/govtool/issues/3397)
> BugFix: #3397, #3399

- pdf-ui/CHANGELOG.md
- pdf-ui/src/lib/helpers.js
- Sign data is part of the [CIP-95 extension](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0095#apicip95signdataaddr-address--drepid-payload-bytes-promisedatasignature) which is the one that is required by GovTool
I've tested this one against already installed node module in GovTool - @nebojsact Could you please verify before merging if that fix is working as expected under your local stack?
- [related issue](https://github.com/IntersectMBO/govtool/issues/3392)
> fix(#3392): fix signing data by calling the CIP-95 extension

- backend/src/extensions/users-permissions/strapi-server.js
- Change secure cookie flag to false to check on deployed version
> fix: check for secure cookie flag

- pdf-ui/src/components/GlobalWrapper.jsx
- change diff time to less or equal to 5 minutes instead of 10
> fix: change diff time to less then  or equal 5 minutes

- pdf-ui/src/pages/BudgetDiscussion/index.jsx
- Rename sorting options to newest and oldest
> feat(#3331): rename sort options to newest and oldest

- backend/src/api/bd/controllers/bd.js
- backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json
- pdf-ui/src/components/BudgetDiscussionCard/index.jsx
- pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionInfo.jsx
- pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionSubmit/index.jsx
- pdf-ui/src/components/BudgetDiscussionParts/ProposalOwnership/index.jsx
- pdf-ui/src/pages/BudgetDiscussion/index.jsx
- Updated step 7 name to privacy policy
- Updated back to budget discussion button name to back to budget proposals
- Updated button Create new Budget Discussion to Create new Budget Proposal
- Updated create new Budget discussion text in draft screen to Create new Budget proposal text
- Updated Budget discussion types filter name to Budget categories as per Figma
- Updated Newest and Oldest sort names to Newest first and Oldest first as per Figma
- Add edit iconButton to BudgetDiscussionCard for the user ehich created it and also handle logic to open that edit modal
- Handle Boolean value for pre-check on Checkbox for agreement on first step of the form
- [related issue](https://github.com/IntersectMBO/govtool/issues/3446)
> 3446 update of step 7 name

- pdf-ui/src/components/BudgetDiscussionsList/index.jsx
- pdf-ui/src/pages/BudgetDiscussion/index.jsx
- Add My proposals and All proposals filter to Budget Discussion, handle reset filters to set to all proposals by default
- [related issue](https://github.com/IntersectMBO/govtool/issues/3353)
> feat(#3353): add my proposals filter to bd

- pdf-ui/src/components/BudgetDiscussionReviewVersions/index.js
- pdf-ui/src/components/CommentCard/Subcomponent/index.jsx
- pdf-ui/src/components/CommentCard/index.jsx
- pdf-ui/src/lib/markdownRenderer.js
- pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx
- Add hyperlinking to specific section in proposal detail in budget discussion
- [related issue](https://github.com/IntersectMBO/govtool/issues/3344)
> 3344 allow hyperlinking to sub heading on budget form

- backend/src/api/bd-costing/content-types/bd-costing/schema.json
- backend/src/extensions/documentation/documentation/1.0.0/full_documentation.json
- Fix for clone fields to be floats
> fix: handle clone fields to be floats

- pdf-ui/src/components/CreationGoveranceAction/Step2.jsx
- Fix for checking value in guardrails script url and hash
> Fix for checking value in guardrails script url and hash

- pdf-ui/src/components/CommentCard/Subcomponent/index.jsx
- Fix Missing Test IDs for PDF components(#2988)
- [related issue](https://github.com/IntersectMBO/govtool/issues/2988)
> fix: Missing Test IDs for PDF components(#2988)

- pdf-ui/src/components/CreateGovernanceActionDialog/index.jsx
-  Fix 
Blank screen appear when change proposal type
> Fix (blank screen appear when change proposal type)

- pdf-ui/src/components/BudgetDiscussionParts/BudgetDiscussionReview/index.jsx
- pdf-ui/src/components/CommentCard/Subcomponent/index.jsx
- pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx
- Change Check for name instead of id for other in SingleBudgetDiscussion and BudgetDiscussionReview, data-testId to testId / Remove Console log in SingleBudgetDiscussion
> fix: check for name instead of id for other

- pdf-ui/CHANGELOG.md
- pdf-ui/package.json
- pdf-ui/src/components/BudgetDiscussionReviewVersions/index.js
- Fix  show other contracting types in budget discussion review and version review / Change version to 28
- [related issue](https://github.com/IntersectMBO/govtool/issues/3553)
> Version change to 28

- pdf-ui/src/pages/BudgetDiscussion/SingleBudgetDiscussion/index.jsx
> Message display fix when submited for vote

- backend/public/api-docs/api.yaml
- backend/src/api/proposal-content/content-types/proposal-content/schema.json
- Add 
Exposed API Flag for Final-State Proposals and Support Lock/Unlock Status for Cosponsor Crowdfunding Integration #3629
- [related issue](https://github.com/IntersectMBO/govtool/issues/3629)
> Added is_locked flag in proposals

- backend/src/extensions/users-permissions/strapi-server.js
- Add 
Added refresh token in login response
- [related issue](https://github.com/IntersectMBO/govtool/issues/3571)
> JWT Refresh token added in login responce #3571

- pdf-ui/src/components/BudgetDiscussionReviewVersions/index.js
- pdf-ui/src/components/ReviewVersions/index.jsx
-  Fix  Versions of the proposals is not scrolled right way
- [related issue](https://github.com/IntersectMBO/govtool/issues/3084)
> fix:  Versions of the proposals is not scrolled right way

- pdf-ui/src/components/BudgetDiscussionsList/index.jsx
- pdf-ui/src/components/ProposalsList/index.jsx
- Add Implement infinite scrolling for Budget Discussions List
- [related issue](https://github.com/IntersectMBO/govtool/issues/3697)
> feat: Implement infinite scrolling for Budget Discussions List

- pdf-ui/CHANGELOG.md
- pdf-ui/package-lock.json
- pdf-ui/package.json
- pdf-ui/src/components/BudgetDiscussionPoll/index.jsx
- Fix voting buttons removed for non drep and version change
- [related issue](https://github.com/IntersectMBO/govtool/issues/3807)
> Fix voting buttons removed for non drep and version change
